# Generated by Django 5.2 on 2025-04-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
