# Generated by Django 5.2 on 2025-04-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_cart', '0002_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
