# Generated by Django 5.2 on 2025-04-13 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0003_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('Product', models.ManyToManyField(related_name='orders', to='ecommerce.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
