# Generated by Django 5.2 on 2025-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total_Price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
