# Generated by Django 5.1.7 on 2025-03-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
