# Generated by Django 5.1.7 on 2025-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=500)),
                ('contact', models.IntegerField(max_length=12)),
                ('department', models.CharField(choices=[('bca', 'BCA'), ('ba', 'BA'), ('bcom', 'BCOM'), ('bba', 'BBA')], max_length=20)),
            ],
        ),
    ]
