# Generated by Django 5.1.7 on 2025-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntry', '0002_alter_profile_contact_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='null', max_length=255, unique=True),
        ),
    ]
