# Generated by Django 5.1.7 on 2025-03-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntry', '0008_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
