# Generated by Django 5.1.7 on 2025-03-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataEntry', '0014_alter_profile_address_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
